---
version: '2'
services:

  zookeeper:
    image: zookeeper:3.6
    command: "bin/zkServer.sh start-foreground"
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    command: "start-kafka.sh"
    container_name: kafka
    environment:
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,AUTHENTICATED://localhost:9094
      KAFKA_LISTENERS: PLAINTEXT://:9092,AUTHENTICATED://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,AUTHENTICATED:SASL_PLAINTEXT
      KAFKA_OPTS: -Djava.security.auth.login.config=/opt/kafka/jaas/kafka_server_jaas.conf
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    volumes:
      - ./kafka_server_jaas.conf:/opt/kafka/jaas/kafka_server_jaas.conf
    links:
      - zookeeper:zookeeper
    ports:
      - 9092:9092
      - 9094:9094
