---
- hosts: kafka
  tasks:
    - command: grep advertised.listeners /opt/kafka/config/server.properties
      register: advertised_listener_command
      changed_when: false

    - debug: var=advertised_listener_command.stdout

    - wait_for:
        port: 9092

- hosts: executors
  gather_facts: false
  tasks:

    - kafka_topic:
        name: scram-test-topic
        state: present
        partitions: 1
        replica_factor: 1
        bootstrap_servers: "{{ bootstrap_servers['plaintext'] }}"


    - kafka_users:
        users:

          - name: 'alice'
            password: changeit
            state: 'present'

          - name: 'bob'
            password: changeit
            mechanism: SCRAM-SHA-256
            iterations: 5000
            state: 'present'

        bootstrap_servers: "{{ bootstrap_servers['plaintext'] }}"
