---
- name: Example | Topic replica update
  hosts: 127.0.0.1
  roles:
    - name: kafka_lib
  post_tasks:
    - name: "Create topic 'test-topic-replica-update'"
      kafka_topic:
        api_version: "2.6.0"
        name: "test-topic-replica-update"
        partitions: 2
        replica_factor: 1
        bootstrap_servers: "localhost:9092,localhost:9093"
        state: "present"

    - name: "Update topic 'test-topic-replica-update'"
      kafka_topic:
        api_version: "2.6.0"
        name: "test-topic-replica-update"
        partitions: 2
        replica_factor: 2
        bootstrap_servers: "localhost:9092,localhost:9093"
        state: "present"

    - name: "Get topics information"
      kafka_info:
        resource: "topic"
        api_version: "2.6.0"
        bootstrap_servers: "localhost:9092"
      register: topics

    - name: "Display results"
      debug:
        var: topics['ansible_module_results']['test-topic-replica-update']
